### ISSUE TITLE
Some improvements to the docker compose file.

### ISSUE THREAD

**Issue by steveiliop56** [lllllllillllllillll/DweebUI#29]
Hello,

Awesome project! Just wanted to point some things out for a docker compose file. Here they are:
1. It would be better to use names like: ```dweeb-redis``` and ```dweeb``` so you can focus on simple names. Something like ```DweebUiCache``` makes things complicated.
2. I would recommend using ```unless-stopped``` on both containers because with the current setup if you stop dweeb with ```docker stop DweebUI``` it wont start unless you start it while redis will : )
3. I saw that you are using redis as cache. Are the data of redis really needed?
4. It would be better to force users to create the dweeb directory since some users may just create a docker-compose file inside their home directory for example.
5. I think bind volumes would be more useful since users may need to access dweeb data.

Thats all! Again awesome project!

**Comment by lllllllillllllillll** [comment]
@steveiliop56  Thanks!
I'll make the changes to the compose file tomorrow, or if you prefer, you could fork the dev branch and make a pull request with the updated compose file. That way I can merge the changes and you'll appear as a contributor.

#3) No, Redis isn't needed at all. I just haven't gotten around to removing it yet.

**Comment by steveiliop56** [comment]
Hello!

Yeah of course I will create a pr soon!

**Comment by lllllllillllllillll** [comment]
I've updated the dev branch to remove redis in v0.07

**Comment by lllllllillllllillll** [comment]
Merged into dev.
These changes will be implemented in v0.08.
