### ISSUE TITLE
Image tab unavailable

### ISSUE THREAD

**Issue by zarevskaya** [lllllllillllllillll/DweebUI#85]
Hello,

When I click on the Image tab, it says page not found.

`DB Connection: ✔
Synced Models: ✔
Listening on http://localhost:8000
file:///app/controllers/images.js:80
        if (container_images.includes(images[i].RepoTags[0])) {
                                                        ^

TypeError: Cannot read properties of null (reading '0')
    at Images (file:///app/controllers/images.js:80:57)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v22.2.0
DB Connection: ✔
Synced Models: ✔
Listening on http://localhost:8000
file:///app/controllers/images.js:80
        if (container_images.includes(images[i].RepoTags[0])) {
                                                        ^

TypeError: Cannot read properties of null (reading '0')
    at Images (file:///app/controllers/images.js:80:57)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v22.2.0
DB Connection: ✔
Synced Models: ✔
Listening on http://localhost:8000`

Any hint? Thanks!

**Comment by lllllllillllllillll** [comment]
Try with `lllllllillllllillll/dweebui:v0.70-dev` instead.

Added try block for images without RepoTags: da9692bdb173f766dfbacafcc2fdb3336b7e4b97

**Comment by zarevskaya** [comment]
Thanks, that work fine ;)
