### ISSUE TITLE
[feat req] allow no-auth to use.

### ISSUE THREAD

**Issue by bingoct** [lllllllillllllillll/DweebUI#88]
add environment or front button to allow no-auth for local personal.

**Comment by lllllllillllllillll** [comment]
Should be available when v0.70 releases.

Added NO_AUTH env: 5e13288fc1efbcb0e832d313053144b397b8bcc3
NO_AUTH routing: 6c15c28c2e3bb7a10470baeff2c235e1d9fbdb47

**Comment by lllllllillllllillll** [comment]
@bingoct It's barely tested, but it's been implemented in v0.70-dev. 

If you have `NO_AUTH: true` in your environment variables, and you're connecting from localhost, you will be logged in as "Localhost / admin" when you press "Sign in".

No username or password required.

Commit: aacc25cd15d10ab81407521b2a70daabff00be6d

**Comment by lllllllillllllillll** [comment]
@bingoct NO_AUTH env should be fully functioning in v0.70-dev now. 

Commit: 935cf1e9952d8238bf68abf33ee2e7249640e7cb
